### ISSUE TITLE
Basic setup instructions?

### ISSUE THREAD

**Issue by tavurth** [Drainful/godot-lisp#1]
Hi nice repo!

Do you have a list of basic setup steps we could follow to reproduce?

**Comment by Drainful** [comment]
I made practically no progress on this. I doubt anyone would find the code here useful, and I'm unlikely to continue working on this in the near future. [godot-python](https://github.com/touilleMan/godot-python) is what I was basing my methodology on if you want to give it a go. I'll make this repo private in a few days.

**Comment by Drainful** [comment]
Well I never got it running. There's very little here that you couldn't get from godot-python. You're right that I might as well leave it open. Feel free to look it over, but there's nothing for me to document.
